<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_post_execute().
 */
function fkg_ct_outcome_views_post_execute(ViewExecutable $view) {
  // Remove duplicated outcomes and the referenced outcome itself.
  // @todo Seek a better solution using hook_views_query_alter().

  // Restrict the result modification to the specified view & display.
  if ($view->id() != 'fkg_outcome_programs' || $view->current_display != 'outcomes') {
    return;
  }

  $view_result = $view->result;
  $exclude_nid = $view->args[0] ?? null;
  $unique_nids = [];
  $view->result = [];
  foreach ($view_result as $item) {
    $nid = $item->node_field_data_node__field_fkg_contrib_outcome_1_nid ?? null;
    if ($nid && $nid != $exclude_nid && !in_array($nid, $unique_nids)) {
      $unique_nids[] = $nid;
      $view->result[] = $item;
    }
  }
}
