<?php

use Drupal\neptune_sync\querier;
/**
 * @file
 * Neptune sync hook implementations.
 * Author: Alexis Harper | Department of Finance 
 */


/**
* Implements hook_cron().
*/
function neptune_sync_cron()
{
    $query_manager = new querier\QueryManager();
    $query_manager->syncAllDatasets();
}

/**
 * Implements hook_theme().
 */
function neptune_sync_theme($existing, $type, $theme, $path) {
  return [
      'graph_template' => [
          'variables' => ['test_var' => NULL],
      ],
  ];
}
    
    
