<?php

/**
 * @file
 * 
 * hook implementations and functions for the module.
 */

/**
 * Implements hook_theme().
 */
function fkg_ct_program_theme($existing, $type, $theme, $path) {
  $qlidev = 'test';
  return [
    'node__fkg_ct_program' => [
      'template' => 'node--fkg-ct-program',
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK() for the node--fkg-ct-program template.
 */
function fkg_ct_program_preprocess_node__fkg_ct_program (&$variables) {
  $node = $variables['node'];
  $node_id = $node->id();
  $program_owner_id = $node->get('field_bodies')->getString();

  // Construct a content element to render the extra Outcome/Expense information.
  $extra_content = [
    '#type' => 'container',
    '#weight' => 10,
    '#attributes' => [
      'class' => ['fkg-program-character-sheet'],
    ],
    '#attached' => [
      'library' => ['fkg_ct_program/fkg_charactersheet_outcome_program'],
    ],
    'outcome' => views_embed_view('fkg_outcome_programs', 'program_outcome', $node_id, $program_owner_id) + [
      '#weight' => '1',
    ],
    'expense' => views_embed_view('fkg_program_expenses', 'default', $node_id) + ['#weight' => '2'],
  ];

  $variables['content']['extra'] = $extra_content;
}
