<?php


namespace Drupal\neptune_sync\Form;


use Drupal\Core\Form\FormStateInterface;

class CoopGraphForm extends \Drupal\Core\Form\FormBase
{

    public function getFormId(){
        return 'coop_graph_form';
    }


    public function buildForm(array $form, FormStateInterface $form_state){




        $form['actions'] = [
            '#type' => 'actions',
            '#tree' => TRUE,
        ];
        $form['actions']['submit'] = [
            '#type' => 'submit',
            '#value' => 'Run query',
            '#button_type' => 'primary',
        ];

        return $form;
    }

    /**
     * @todo this could use some work in a future sprint
     * @param array $form
     * @param FormStateInterface $form_state
     */
    public function validateForm(array &$form, FormStateInterface $form_state){
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function submitForm(array &$form, FormStateInterface $form_state)
    {
        // TODO: Implement submitForm() method.
    }
}