<?php

namespace Drupal\neptune_sync\Form;


use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

class LocalGraphForm extends FormBase {


    public function getFormId()
    {
        return 'local_graph_form';
    }

    public function buildForm(array $form, FormStateInterface $form_state, $node = null)
    {
        $x =\Drupal\Webform\Entity\Webform::load('local_grapgh_query');
        //kint($x, 'pre getSubmissionForm');
        $y = \Drupal::entityManager()
            ->getViewBuilder('webform')
            ->view($x);
       //kint($y, 'form view ');
        //kint($form);

        return $y;
    }

    public function validateForm(array &$form, FormStateInterface $form_state)
    {
        parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
    }

    public function  submitForm(array &$form, FormStateInterface $form_state)
    {
        // TODO: Implement submitForm() method.
    }
}