<?php

/**
 * @file
 */

use Drupal\Core\Entity\Exception;

/**
 * Implements hook_preprocess_paragraph().
 */
function fkg_ct_body_preprocess_paragraph(&$variables) {

  $sections_annual_report = [
    'Non-corporate Commonwealth entity' => [
      'section' => 'section 46 of the PGPA Act',
      'href' => 'https://www.legislation.gov.au/Details/C2017C00269/Html/Text#_Toc491697420'  
    ],
    'Corporate Commonwealth entity' => [
      'section' => 'section 46 of the PGPA Act',
      'href' => 'https://www.legislation.gov.au/Details/C2017C00269/Html/Text#_Toc491697420'  
    ],
    'Commonwealth company' => [
      'section' => 'section 97 of the PGPA Act',
      'href' => 'https://www.legislation.gov.au/Details/C2017C00269/Html/Text#_Toc491697507'
    ]
  ];

  $paragraph = $variables['paragraph'];

  // Get the Body type of the parent entity.
  try {
    $term_body_type = $paragraph->getParentEntity()->get('field_type_of_body')->entity;
    $term_label_body_type = $term_body_type ? $term_body_type->label : '';
  }
  catch (Exception $e) {}

  // Determine the content of the applicable legislation section according to the Body type and add it to the rendering.
  if ($term_label_body_type && array_key_exists($term_label_body_type, $sections_annual_report)) {
    $placeholder = $sections_annual_report[$term_label_body_type];
    $markup_report_type = [
      '#type' => 'markup',
      '#markup' => t('Annual report prepared under <a target="_blank" href="@href">@section</a>.', ['@href' => $placeholder['href'], '@section' => $placeholder['section']]),
      '#weight' => -5,
    ];

    if ($term_label_body_type === 'Commonwealth company') {
      $variables['content'] = [
        'report_type' => $markup_report_type,
      ];
    }
    else {
      $variables['content']['report_type'] = $markup_report_type;
    }
  }
}
